<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */

namespace App\Controller;

use App\Model\Entity\Role;
use App\Model\Entity\Staff;
use Cake\Controller\Controller;
use Cake\Event\EventInterface;
use Cake\Mailer\Mailer;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize();
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('FormProtection');
//        if ($this->request->prefix == 'Staff') {

//            dd($this->request->prefix);
        $this->loadComponent('Auth', [
            'authenticate' => [
                'Form' => [
                    'fields' => [
                        'username' => 'username',
                        'password' => 'password'
                    ],
                    'userModel' => 'Staffs'
                ]
            ],
            'loginAction' => [
                'controller' => 'Staffs',
                'action' => 'login'
            ],
//            'loginRedirect' => [
//                'plugin' => null,
//                'controller' => 'Faqs',
//                'action' => 'general'
//            ],
            'logoutRedirect' => [
                'plugin' => null,
                'controller' => 'Staffs',
                'action' => 'login'
            ],
            'authError' => 'You are not authorized to access that location.',
            'flash' => [
                'element' => 'error'
            ]
        ]);
        $this->Auth->allow(['logout', 'login']);

    }



    /*
     * Enable the following component for recommended CakePHP form protection settings.
     * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
     */
    //$this->loadComponent('FormProtection');

    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $login = null;

        if ($this->Auth->user()) {
            $login = $this->Auth->user();
            $this->set(compact('login'));
        }
    }
//    public function send_mail($email_data = null)
//    {
//        //echo "<pre>";print_r($email_data);die;
//        //echo WWW_ROOT;die;
//        $email = new Mailer('default');
//        $email_to = $email_data['to'];
//        $email_msg = $email_data['body'];
//        $email_subject = $email_data['subject'];
//
//        $email->setTo($email_to);
//        $email->setSubject($email_subject);
//        $mail_status = @$email->send($email_msg);
//
//        if (!$mail_status) {
//            return FALSE;
//        }
//        return TRUE;
//    }
}
