<?php
declare(strict_types=1);

namespace App\Controller;


use App\Model\Entity\Staff;
use App\Model\Table\StaffsTable;
use Cake\Core\App;
use Cake\Datasource\ResultSetInterface;
use Cake\Mailer\Mailer;
use Cake\ORM\TableRegistry;
use Cake\Utility\Security;
use mysql_xdevapi\Table;


/**
 * Staffs Controller
 * @property \App\Model\Table\StaffsTable $Staffs
 * @property \App\Model\Table\SolutionsTable $Solutions
 *  @property \App\Model\Table\TicketsTable $Tickets
 * @property \App\Model\Table\CategoriesTable $Categories
 * @method Staff[]|ResultSetInterface paginate($object = null, array $settings = [])
 *

 */
class  AssistantsController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Solutions = $this->fetchTable('Solutions');
        $this->Tickets = $this->fetchTable('Tickets');
        $this->Staffs = $this->fetchTable('Staffs');


        $roleID = $this->Auth->user('role_id');
        if ($roleID == '4') {
            $this->viewBuilder()->setLayout('userdefault');
        }
        elseif ($roleID == '11') {
            $this->viewBuilder()->setLayout('assistantdefault');

    }
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|null|void Renders view
     */


    public function general()
    {
        $this->viewBuilder()->setLayout('assistantdefault');
        $this->paginate = ['contain' => 'Assistants'];
        $solutions = $this->Solutions->find()->all();
        $this->set(compact('solutions'));
    }

    public function bank()
    {
        $this->viewBuilder()->setLayout('assistantdefault');
        $this->paginate = ['contain' => 'Solutions', 'Categories'];

        $solutions = $this->Solutions->find()->where(['category_id' => 1]);
//        dd($solutions);
//        if ($this->request->is('post')) {
//            $this->redirect('staffs/faq');
//        }
        $this->set(compact('solutions'));
    }

    public function it()
    {
        $this->viewBuilder()->setLayout('assistantdefault');
        $this->paginate = ['contain' => 'Solutions', 'Categories'];

        $solutions = $this->Solutions->find()->where(['category_id' => 2]);
//        dd($solutions);
//        if ($this->request->is('post')) {
//            $this->redirect('staffs/faq');
//        }
        $this->set(compact('solutions'));
    }

    public function school()
    {
        $this->viewBuilder()->setLayout('assistantdefault');
        $this->paginate = ['contain' => 'Solutions', 'Categories'];

        $solutions = $this->Solutions->find()->where(['category_id' => 3]);
//        dd($solutions);
//        if ($this->request->is('post')) {
//            $this->redirect('staffs/faq');
//        }
        $this->set(compact('solutions'));
    }

    public function ticketAssigned()
    {
        $this->viewBuilder()->setLayout('assistantdefault');

        $this->paginate = [
            'contain' => ['Status', 'Staffs'],
        ];
        $key = $this->request->getQuery('key');
        $query = $this->Staffs->Tickets->find()->where(['staff_id'=> $this->Auth->user('id')]);

        $tickets = $this->paginate($query, ['limit' => 10]);
//        $this->Tickets->Status->get($tickets['id']);




        $this->set(compact('tickets'));
    }


    public function view($id = null)
    {
        $ticket = $this->Tickets->get($id, [
            'contain' => ['Status','Staffs'],
        ]);
        $this->set(compact('ticket'));
        return $this->redirect(['controller'=>'Reply','action'=>'index',$id]);
    }
//    for submitted tickets
    public function edit($id = null)
    {
        $ticket = $this->Tickets->get($id, [
            'contain' => ['Status','Staffs'],
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $ticket = $this->Tickets->patchEntity($ticket, $this->request->getData());
            if ($this->Tickets->save($ticket)) {
                $this->Flash->success(__('The ticket has been saved.'));

                return $this->redirect(['action' => 'ticketAssigned']);
            }
            $this->Flash->error(__('The ticket could not be saved. Please, try again.'));
        }
        $staffs = $this->Tickets->Staffs->find('list', ['limit' => 200])->all();
        $status = $this->Tickets->Status->find('list', ['limit' => 200])->all();

        $this->set(compact('ticket', 'staffs','status'));
    }

    public function submitTicketAlert($id){
        $user_id = $this->Tickets->get($id);
        $user = $this->Tickets->Staffs->get($user_id['submit_by']);

//            dd($myEmail);
        $mailer = new Mailer();
        $mailer->setTransport('gmail');
        $mailer
            ->setTo('rathmuny85@gmail.com')
            ->setEmailFormat('html')
            ->setSubject('Help Desk_Submit Notification 🔔')
            ->setViewVars(['name'=>$user->staffName])

            ->viewBuilder()
            ->setTemplate('submitTicketAlert');

        if ($mailer->deliver()) {
            $this->Flash->success('Submit notification has been sent to admin email');
        }
    }
    public function submitTicket()
    {
        $this->viewBuilder()->setLayout('ajax');
        $data = $this->getRequest()->getData();
        $data['status_id'] = 1;
        $data['staff_id'] = 64;
        $data['submit_by'] = $this->Auth->user('id');

        $ticket = $this->Tickets->newEmptyEntity();
        if ($this->request->is('post')) {
            $ticket = $this->Tickets->patchEntity($ticket, $data);
//            dd($ticket);
            if ($this->Tickets->save($ticket)) {
                $this->Flash->success(__('The ticket has been saved.'));
                $this->submitTicketAlert($ticket['id']);


                return $this->redirect(['action' => 'ticket_assigned']);
            }
            $this->Flash->error(__('The ticket could not be saved. Please, try again.'));
        }
        $categories = $this->Tickets->Categories->find('list', ['limit' => 200])->all();
        $this->set(compact('ticket', 'categories'));
    }


}

