<?php
namespace App\Controller;
/**
 * @var \App\View\AppView $this
 * @property \App\Model\Table\TicketsTable $Tickets

 */

use App\Controller\AppController;
use App\Model\Entity\Ticket;

class DashboardController extends AppController{

    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Tickets = $this->fetchTable('Tickets');
    }

    public function dashboard()
    {
//        $this->set('count_tutorial', $this->Tickets->find()->where(['status_id' => '1'])->count());
//        $this->set('count_blog', $this->Tickets->find()->where(['status_id' => '2'])->count());
//        $this->set('count_project', $this->Tickets->find()->where(['status_id' => '3'])->count());    }

    }
    }

